name: "Update locales sources"

on:
  push:
    branches:
      - "main"

jobs:
  push-on-transifex:
    if: github.repository == 'pluginsGLPI/fields'
    name: "Push locales sources"
    uses: "glpi-project/plugin-translation-workflows/.github/workflows/transifex-push-sources.yml@v1"
    secrets:
      transifex-token: "${{ secrets.TRANSIFEX_TOKEN }}"
